plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    # Restore defaults (overridden when specifying custom excludes)
    - ".git/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    # Project-specific
    - "spec/grpc_smoke_spec.rb"

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 120
  Exclude:
    - "lib/busybee/grpc/gateway_pb.rb"
    - "lib/busybee/grpc/gateway_services_pb.rb"

Lint/UselessDefaultValueArgument:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "lib/busybee/testing/matchers/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 150

Naming/VariableNumber:
  Exclude:
    - "spec/**/*"

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"
    - "spec/**/matchers/**/*"

RSpec/ExampleLength:
  Max: 15
  Exclude:
    - "spec/integration/**/*"

RSpec/MessageSpies:
  EnforcedStyle: have_received

RSpec/MultipleExpectations:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/integration/**/*"

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantStringEscape:
  Exclude:
    - "lib/busybee/grpc/gateway_pb.rb"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
