#!/usr/bin/env bash

# gen-grpc.sh - Generate Ruby GRPC code from Zeebe protocol buffers
#
# This script:
# 1. Reads the ZEEBE_VERSION from .env
# 2. Downloads gateway.proto from the Camunda GitHub repository
# 3. Generates Ruby code using grpc_tools_ruby_protoc
# 4. Fixes namespacing to use Busybee::GRPC module structure
#
# Usage: ./gen-grpc.sh
# Or via rake: rake grpc:generate

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}==> Starting GRPC code generation${NC}"

# Load ZEEBE_VERSION from .env
if [ ! -f .env ]; then
  echo -e "${RED}Error: .env file not found${NC}"
  exit 1
fi

# Extract ZEEBE_VERSION from .env (handles comments and whitespace)
ZEEBE_VERSION=$(grep -E "^ZEEBE_VERSION=" .env | cut -d '=' -f2 | tr -d ' ' | tr -d '"' | tr -d "'")

if [ -z "$ZEEBE_VERSION" ]; then
  echo -e "${RED}Error: ZEEBE_VERSION not found in .env${NC}"
  exit 1
fi

echo -e "${YELLOW}==> Using Zeebe version: ${ZEEBE_VERSION}${NC}"

# Download gateway.proto
PROTO_URL="https://raw.githubusercontent.com/camunda/camunda/refs/tags/${ZEEBE_VERSION}/zeebe/gateway-protocol/src/main/proto/gateway.proto"
PROTO_FILE="proto/gateway.proto"

echo -e "${YELLOW}==> Downloading gateway.proto from ${PROTO_URL}${NC}"

if curl -f -L -o "$PROTO_FILE" "$PROTO_URL"; then
  echo -e "${GREEN}==> Downloaded gateway.proto successfully${NC}"
else
  echo -e "${RED}Error: Failed to download gateway.proto${NC}"
  echo -e "${RED}Please verify that version ${ZEEBE_VERSION} exists at:${NC}"
  echo -e "${RED}${PROTO_URL}${NC}"
  exit 1
fi

# Generate Ruby code using grpc_tools_ruby_protoc
echo -e "${YELLOW}==> Generating Ruby code from protocol buffers${NC}"

if ! command -v grpc_tools_ruby_protoc &> /dev/null; then
  echo -e "${RED}Error: grpc_tools_ruby_protoc not found${NC}"
  echo -e "${RED}Please run: bundle install${NC}"
  exit 1
fi

# Use -I to specify proto path, this keeps the output clean
grpc_tools_ruby_protoc -I proto \
  --ruby_out=lib/busybee/grpc \
  --grpc_out=lib/busybee/grpc \
  gateway.proto

echo -e "${GREEN}==> Generated Ruby files${NC}"

# Fix namespacing in gateway_pb.rb
echo -e "${YELLOW}==> Fixing namespacing in gateway_pb.rb${NC}"

GATEWAY_PB="lib/busybee/grpc/gateway_pb.rb"

# Create temporary file with Busybee::GRPC namespace wrapping
{
  echo "# frozen_string_literal: true"
  echo ""
  echo "# Generated by grpc_tools_ruby_protoc - DO NOT EDIT MANUALLY"
  echo "# Regenerate with: rake grpc:generate"
  echo ""
  echo "module Busybee"
  echo "  module GRPC"
  # Add the original content (skip the first line if it's a shebang or frozen_string_literal)
  tail -n +2 "$GATEWAY_PB" | sed 's/^/    /'
  echo "  end"
  echo "end"
} > "${GATEWAY_PB}.tmp"

mv "${GATEWAY_PB}.tmp" "$GATEWAY_PB"

# Remove 'module GatewayProtocol' line and one 'end' from the chain at the bottom
# Rubocop will fix indentation afterward
sed -i '' '/^[[:space:]]*module GatewayProtocol$/d' "$GATEWAY_PB"
sed -i '' '$ d' "$GATEWAY_PB"

echo -e "${GREEN}==> Fixed namespacing in gateway_pb.rb${NC}"

# Fix namespacing in gateway_services_pb.rb
echo -e "${YELLOW}==> Fixing namespacing in gateway_services_pb.rb${NC}"

GATEWAY_SERVICES_PB="lib/busybee/grpc/gateway_services_pb.rb"

# Create temporary file with Busybee::GRPC namespace wrapping and fixed require
{
  echo "# frozen_string_literal: true"
  echo ""
  echo "# Generated by grpc_tools_ruby_protoc - DO NOT EDIT MANUALLY"
  echo "# Regenerate with: rake grpc:generate"
  echo ""
  echo "module Busybee"
  echo "  module GRPC"
  # Add the original content, fix require path, and indent
  tail -n +2 "$GATEWAY_SERVICES_PB" | \
    sed "s|require 'gateway_pb'|require 'busybee/grpc/gateway_pb'|" | \
    sed 's/^/    /'
  echo "  end"
  echo "end"
} > "${GATEWAY_SERVICES_PB}.tmp"

mv "${GATEWAY_SERVICES_PB}.tmp" "$GATEWAY_SERVICES_PB"

# Remove 'module GatewayProtocol' line and one 'end' from the chain at the bottom
# Rubocop will fix indentation afterward
sed -i '' '/^[[:space:]]*module GatewayProtocol$/d' "$GATEWAY_SERVICES_PB"
sed -i '' '$ d' "$GATEWAY_SERVICES_PB"

# Remove GatewayProtocol:: prefix from class references (now they're in the same namespace)
# Handle both ::GatewayProtocol:: and GatewayProtocol:: patterns
sed -i '' 's/::GatewayProtocol:://g' "$GATEWAY_SERVICES_PB"
sed -i '' 's/GatewayProtocol:://g' "$GATEWAY_SERVICES_PB"

echo -e "${GREEN}==> Fixed namespacing in gateway_services_pb.rb${NC}"

# Fix indentation using rubocop
echo -e "${YELLOW}==> Running rubocop to fix formatting${NC}"
bundle exec rubocop -A "$GATEWAY_PB" "$GATEWAY_SERVICES_PB" --only Layout || true

echo -e "${GREEN}==> GRPC code generation complete!${NC}"
echo ""
echo "Generated files:"
echo "  - lib/busybee/grpc/gateway_pb.rb"
echo "  - lib/busybee/grpc/gateway_services_pb.rb"
echo ""
echo "All classes are in the Busybee::GRPC namespace"
